version: '3'
services:
  pdp-service:
    image: permitio/pdp-v2:latest
    ports:
      - '7766:7000'
    environment:
      - PDP_API_KEY=${PDP_API_KEY:-permit_key_REPLACE_ME}
      - PDP_DEBUG=True
    stdin_open: true
    tty: true
